In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Recommend.csv',names =['user_id','movie_id','rating','timestamp'])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [3]:
n_users = df.user_id.unique().shape[0]
n_movies = df.movie_id.unique().shape[0]
print("total number of users ",n_users,"\ntotal number of movies",n_movies)

total number of users  943 
total number of movies 1682


In [4]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df,test_size =0.25)

In [5]:
train_data_matrix = np.zeros((n_users,n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1] = line[3]
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
test_data_matrix = np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [7]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric ='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric ='cosine')
mean_user_rating = train_data_matrix.mean(axis = 1)[:,np.newaxis]
ratings_diff = (train_data_matrix - mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.56018779,  0.5609877 ,  0.48687256, ...,  0.29058216,
         0.29055779,  0.29039897],
       [ 1.28318857,  0.27001694,  0.16250745, ..., -0.06451924,
        -0.06325931, -0.06310219],
       [ 1.31577143,  0.23295443,  0.13460068, ..., -0.09998785,
        -0.09824201, -0.09805129],
       ...,
       [ 1.1772712 ,  0.20337858,  0.10012636, ..., -0.11651041,
        -0.11562141, -0.1154796 ],
       [ 1.34343554,  0.29450695,  0.2185136 , ..., -0.0082382 ,
        -0.00749841, -0.00735423],
       [ 1.39067283,  0.37470453,  0.30395261, ...,  0.10364352,
         0.10348649,  0.10358501]])